name: navasankalp_application
description: "A new Flutter project."
publish_to: 'none' 
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.5
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^17.0.0
  flutter_spinkit: ^5.2.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: 6.1.0
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  razorpay_flutter: ^1.3.5
  responsive_framework: ^1.1.1
  snap_scroll_physics: ^0.0.1+3
  sticky_headers: ^0.3.0+2
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  intl: ^0.19.0
  loading_animation_widget: ^1.2.0+4
  device_info_plus: ^10.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: NavaSankalp
      fonts:
        - asset: fonts/NavaSankalp.ttf
 
 
  