// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkpKkXsm8K_ezvtWjKjbodEDvfhe1xR0w',
    appId: '1:761849461795:web:6a19803e6bcddb69a48596',
    messagingSenderId: '761849461795',
    projectId: 'navasankalp-dd551',
    authDomain: 'navasankalp-dd551.firebaseapp.com',
    storageBucket: 'navasankalp-dd551.appspot.com',
    measurementId: 'G-L61HVSTN16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVVZBk7QR2DGFL4aS45VacBp-bSM_RzG0',
    appId: '1:761849461795:android:d0c82511c9290a0ba48596',
    messagingSenderId: '761849461795',
    projectId: 'navasankalp-dd551',
    storageBucket: 'navasankalp-dd551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDr7fF7Y6ssAyFeuplNqmD6gtklLmUmuA',
    appId: '1:761849461795:ios:c32c950c4fd1e0ffa48596',
    messagingSenderId: '761849461795',
    projectId: 'navasankalp-dd551',
    storageBucket: 'navasankalp-dd551.appspot.com',
    androidClientId: '761849461795-08b8ed1lgp82443i87erbvg3hli9ceu9.apps.googleusercontent.com',
    iosClientId: '761849461795-8598lbrur4f19h4tlfmsl1kd6j9p0rce.apps.googleusercontent.com',
    iosBundleId: 'com.dcc.navasankalp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDr7fF7Y6ssAyFeuplNqmD6gtklLmUmuA',
    appId: '1:761849461795:ios:5b9efa5c9ca0bc9ea48596',
    messagingSenderId: '761849461795',
    projectId: 'navasankalp-dd551',
    storageBucket: 'navasankalp-dd551.appspot.com',
    androidClientId: '761849461795-08b8ed1lgp82443i87erbvg3hli9ceu9.apps.googleusercontent.com',
    iosClientId: '761849461795-kdfbj1tirro8urdp7vggab72na29d8ka.apps.googleusercontent.com',
    iosBundleId: 'com.dcc.navasankalp.RunnerTests',
  );
}
