/// Flutter icons NavaSankalp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavaSankalp
///      fonts:
///       - asset: fonts/NavaSankalp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class NavaSankalp {
  NavaSankalp._();

  static const _kFontFam = 'NavaSankalp';
  static const String? _kFontPkg = null;

  static const IconData bell = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData arrow_downwards = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuLeft = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData threeDotMenu = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData notification_solid_badged = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData policy = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData arrow_up_icon = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData historyicons = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directory = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slogan = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expandLess = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nameicon = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData address_icon = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData mobile_icon = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData plus_icon = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
